#!/bin/bash

if [ ! -f "rabbitmq-server-generic-unix-3.3.5.tar.gz" ]; then
    wget http://www.rabbitmq.com/releases/rabbitmq-server/v3.3.5/rabbitmq-server-generic-unix-3.3.5.tar.gz
fi

docker build -t rabbitmq .
