#!/bin/bash

if [ ! -f "elasticsearch-1.3.2.tar.gz" ]; then
    wget http://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.3.2.tar.gz
fi

if [ ! -f "logstash-1.4.2.tar.gz" ]; then
    wget http://download.elasticsearch.org/logstash/logstash/logstash-1.4.2.tar.gz
fi

if [ ! -f "kibana-3.1.0.tar.gz" ]; then
    wget http://download.elasticsearch.org/kibana/kibana/kibana-3.1.0.tar.gz
fi

docker build -t elk .
