if has('gui_gtk2')
  "set guifont=Bitstream\ Vera\ Sans\ Mono\ 15
  set guifont=Monaco\ 16
  set guifontwide=WenQuanYi\ Micro\ Hei\ Mono\ 15
else
  set guifont=-misc-fixed-medium-r-normal--14-130-75-75-c-70-iso8859-1
endif

"设置启动时窗口的大小
set lines=40
set columns=115

"设置启动时窗口的位置
winpos 0 0
